# Generated by Django 4.0.4 on 2024-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_fullname_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
